paths:
  # cldf: ../yawarana-corpus-cldf/full/metadata.json
  cldf: cldf/metadata.json
  add_bib: extra/cariban.bib
  audio: ../corpus/audio
data:
  data: true
  rich: true
output:
  readme: false
  build:
    - mkdocs
    - plain
    - latex
    # - docx
  preview: html
  changelog: true
mkdocs:
  audio: true
examples:
  show_language: false
  # custom_links:
  #   💻: http://localhost:6543/sentences/{id}
  #   🖉: http://localhost:5001/example/{id}
lfts:
  show_language: false
  show_source: false
input:
  sublime: false
releasing:
  zip:
    cldf: true
    latex:
      - main.pdf: A digital sketch grammar of Yawarana.pdf
    mkdocs:
      - site: html
    plain:
      - document.txt: plain.txt