site_url: https://caribank.github.io/yawarana-sketch/
theme:
  palette:     
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light markdown_extensions